INSERT INTO City VALUES (N'آذربایجان شرقی',N'کشکسرای');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'سهند');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'سیس');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'دوزدوزان');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'تیمورلو');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'صوفیان');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'سردرود');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'هادیشهر');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'هشترود');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'زرنق');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'ترکمانچای');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'ورزقان');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'تسوج');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'زنوز');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'ایلخچی');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'شرفخانه');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'مهربان');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'مبارک شهر');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'تیکمه داش');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'باسمنج');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'سیه رود');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'میانه');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'خمارلو');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'خواجه');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'بناب مرند');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'قره آغاج');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'وایقان');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'مراغه');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'ممقان');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'خامنه');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'خسروشاه');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'لیلان');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'نظرکهریزی');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'اهر');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'بخشایش');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'آقکند');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'جوان قلعه');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'کلیبر');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'مرند');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'اسکو');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'شندآباد');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'شربیان');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'گوگان');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'بستان آباد');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'تبریز');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'جلفا');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'اچاچی');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'هریس');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'یامچی');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'خاروانا');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'کوزه کنان');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'خداجو(خراجو)');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'آذرشهر');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'شبستر');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'سراب');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'ملکان');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'بناب');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'هوراند');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'کلوانق');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'ترک');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'عجب شیر');
INSERT INTO City VALUES (N'آذربایجان شرقی',N'آبش احمد');
INSERT INTO City VALUES (N'آذربایجان غربی',N'تازه شهر');
INSERT INTO City VALUES (N'آذربایجان غربی',N'نالوس');
INSERT INTO City VALUES (N'آذربایجان غربی',N'ایواوغلی');
INSERT INTO City VALUES (N'آذربایجان غربی',N'شاهین دژ');
INSERT INTO City VALUES (N'آذربایجان غربی',N'گردکشانه');
INSERT INTO City VALUES (N'آذربایجان غربی',N'باروق');
INSERT INTO City VALUES (N'آذربایجان غربی',N'سیلوانه');
INSERT INTO City VALUES (N'آذربایجان غربی',N'بازرگان');
INSERT INTO City VALUES (N'آذربایجان غربی',N'نازک علیا');
INSERT INTO City VALUES (N'آذربایجان غربی',N'ربط');
INSERT INTO City VALUES (N'آذربایجان غربی',N'تکاب');
INSERT INTO City VALUES (N'آذربایجان غربی',N'دیزج دیز');
INSERT INTO City VALUES (N'آذربایجان غربی',N'سیمینه');
INSERT INTO City VALUES (N'آذربایجان غربی',N'نوشین');
INSERT INTO City VALUES (N'آذربایجان غربی',N'میاندوآب');
INSERT INTO City VALUES (N'آذربایجان غربی',N'مرگنلر');
INSERT INTO City VALUES (N'آذربایجان غربی',N'سلماس');
INSERT INTO City VALUES (N'آذربایجان غربی',N'آواجیق');
INSERT INTO City VALUES (N'آذربایجان غربی',N'قطور');
INSERT INTO City VALUES (N'آذربایجان غربی',N'محمودآباد');
INSERT INTO City VALUES (N'آذربایجان غربی',N'خوی');
INSERT INTO City VALUES (N'آذربایجان غربی',N'نقده');
INSERT INTO City VALUES (N'آذربایجان غربی',N'سرو');
INSERT INTO City VALUES (N'آذربایجان غربی',N'خلیفان');
INSERT INTO City VALUES (N'آذربایجان غربی',N'پلدشت');
INSERT INTO City VALUES (N'آذربایجان غربی',N'میرآباد');
INSERT INTO City VALUES (N'آذربایجان غربی',N'اشنویه');
INSERT INTO City VALUES (N'آذربایجان غربی',N'زرآباد');
INSERT INTO City VALUES (N'آذربایجان غربی',N'بوکان');
INSERT INTO City VALUES (N'آذربایجان غربی',N'پیرانشهر');
INSERT INTO City VALUES (N'آذربایجان غربی',N'چهاربرج');
INSERT INTO City VALUES (N'آذربایجان غربی',N'قوشچی');
INSERT INTO City VALUES (N'آذربایجان غربی',N'شوط');
INSERT INTO City VALUES (N'آذربایجان غربی',N'ماکو');
INSERT INTO City VALUES (N'آذربایجان غربی',N'سیه چشمه');
INSERT INTO City VALUES (N'آذربایجان غربی',N'سردشت');
INSERT INTO City VALUES (N'آذربایجان غربی',N'کشاورز');
INSERT INTO City VALUES (N'آذربایجان غربی',N'فیرورق');
INSERT INTO City VALUES (N'آذربایجان غربی',N'محمدیار');
INSERT INTO City VALUES (N'آذربایجان غربی',N'ارومیه');
INSERT INTO City VALUES (N'آذربایجان غربی',N'مهاباد');
INSERT INTO City VALUES (N'آذربایجان غربی',N'قره ضیاءالدین');
INSERT INTO City VALUES (N'اردبیل',N'پارس آباد');
INSERT INTO City VALUES (N'اردبیل',N'فخراباد');
INSERT INTO City VALUES (N'اردبیل',N'کلور');
INSERT INTO City VALUES (N'اردبیل',N'نیر');
INSERT INTO City VALUES (N'اردبیل',N'اردبیل');
INSERT INTO City VALUES (N'اردبیل',N'اسلام اباد');
INSERT INTO City VALUES (N'اردبیل',N'تازه کندانگوت');
INSERT INTO City VALUES (N'اردبیل',N'مشگین شهر');
INSERT INTO City VALUES (N'اردبیل',N'جعفرآباد');
INSERT INTO City VALUES (N'اردبیل',N'نمین');
INSERT INTO City VALUES (N'اردبیل',N'اصلاندوز');
INSERT INTO City VALUES (N'اردبیل',N'مرادلو');
INSERT INTO City VALUES (N'اردبیل',N'خلخال');
INSERT INTO City VALUES (N'اردبیل',N'کوراییم');
INSERT INTO City VALUES (N'اردبیل',N'هیر');
INSERT INTO City VALUES (N'اردبیل',N'گیوی');
INSERT INTO City VALUES (N'اردبیل',N'گرمی');
INSERT INTO City VALUES (N'اردبیل',N'لاهرود');
INSERT INTO City VALUES (N'اردبیل',N'هشتجین');
INSERT INTO City VALUES (N'اردبیل',N'عنبران');
INSERT INTO City VALUES (N'اردبیل',N'تازه کند');
INSERT INTO City VALUES (N'اردبیل',N'قصابه');
INSERT INTO City VALUES (N'اردبیل',N'رضی');
INSERT INTO City VALUES (N'اردبیل',N'سرعین');
INSERT INTO City VALUES (N'اردبیل',N'بیله سوار');
INSERT INTO City VALUES (N'اردبیل',N'آبی بیگلو');
INSERT INTO City VALUES (N'اصفهان',N'گزبرخوار');
INSERT INTO City VALUES (N'اصفهان',N'زیار');
INSERT INTO City VALUES (N'اصفهان',N'زرین شهر');
INSERT INTO City VALUES (N'اصفهان',N'گلشن');
INSERT INTO City VALUES (N'اصفهان',N'پیربکران');
INSERT INTO City VALUES (N'اصفهان',N'خالدآباد');
INSERT INTO City VALUES (N'اصفهان',N'سجزی');
INSERT INTO City VALUES (N'اصفهان',N'گوگد');
INSERT INTO City VALUES (N'اصفهان',N'تیران');
INSERT INTO City VALUES (N'اصفهان',N'ونک');
INSERT INTO City VALUES (N'اصفهان',N'دهق');
INSERT INTO City VALUES (N'اصفهان',N'زواره');
INSERT INTO City VALUES (N'اصفهان',N'کاشان');
INSERT INTO City VALUES (N'اصفهان',N'ابوزیدآباد');
INSERT INTO City VALUES (N'اصفهان',N'اصغرآباد');
INSERT INTO City VALUES (N'اصفهان',N'بافران');
INSERT INTO City VALUES (N'اصفهان',N'شهرضا');
INSERT INTO City VALUES (N'اصفهان',N'خور');
INSERT INTO City VALUES (N'اصفهان',N'مجلسی');
INSERT INTO City VALUES (N'اصفهان',N'هرند');
INSERT INTO City VALUES (N'اصفهان',N'فولادشهر');
INSERT INTO City VALUES (N'اصفهان',N'کمشچه');
INSERT INTO City VALUES (N'اصفهان',N'کلیشادوسودرجان');
INSERT INTO City VALUES (N'اصفهان',N'لای بید');
INSERT INTO City VALUES (N'اصفهان',N'قهجاورستان');
INSERT INTO City VALUES (N'اصفهان',N'چرمهین');
INSERT INTO City VALUES (N'اصفهان',N'رزوه');
INSERT INTO City VALUES (N'اصفهان',N'فریدونشهر');
INSERT INTO City VALUES (N'اصفهان',N'طرق رود');
INSERT INTO City VALUES (N'اصفهان',N'نصرآباد');
INSERT INTO City VALUES (N'اصفهان',N'برزک');
INSERT INTO City VALUES (N'اصفهان',N'سفیدشهر');
INSERT INTO City VALUES (N'اصفهان',N'سمیرم');
INSERT INTO City VALUES (N'اصفهان',N'گلدشت');
INSERT INTO City VALUES (N'اصفهان',N'اردستان');
INSERT INTO City VALUES (N'اصفهان',N'جوشقان قالی');
INSERT INTO City VALUES (N'اصفهان',N'بویین ومیاندشت');
INSERT INTO City VALUES (N'اصفهان',N'کرکوند');
INSERT INTO City VALUES (N'اصفهان',N'درچه');
INSERT INTO City VALUES (N'اصفهان',N'انارک');
INSERT INTO City VALUES (N'اصفهان',N'دولت آباد');
INSERT INTO City VALUES (N'اصفهان',N'ایمانشهر');
INSERT INTO City VALUES (N'اصفهان',N'گرگاب');
INSERT INTO City VALUES (N'اصفهان',N'حسن اباد');
INSERT INTO City VALUES (N'اصفهان',N'سده لنجان');
INSERT INTO City VALUES (N'اصفهان',N'حبیب آباد');
INSERT INTO City VALUES (N'اصفهان',N'بهاران شهر');
INSERT INTO City VALUES (N'اصفهان',N'میمه');
INSERT INTO City VALUES (N'اصفهان',N'تودشک');
INSERT INTO City VALUES (N'اصفهان',N'گلشهر');
INSERT INTO City VALUES (N'اصفهان',N'رضوانشهر');
INSERT INTO City VALUES (N'اصفهان',N'داران');
INSERT INTO City VALUES (N'اصفهان',N'علویجه');
INSERT INTO City VALUES (N'اصفهان',N'نیک آباد');
INSERT INTO City VALUES (N'اصفهان',N'مشکات');
INSERT INTO City VALUES (N'اصفهان',N'آران وبیدگل');
INSERT INTO City VALUES (N'اصفهان',N'خوانسار');
INSERT INTO City VALUES (N'اصفهان',N'نجف آباد');
INSERT INTO City VALUES (N'اصفهان',N'منظریه');
INSERT INTO City VALUES (N'اصفهان',N'فرخی');
INSERT INTO City VALUES (N'اصفهان',N'دیزیچه');
INSERT INTO City VALUES (N'اصفهان',N'اژیه');
INSERT INTO City VALUES (N'اصفهان',N'زاینده رود');
INSERT INTO City VALUES (N'اصفهان',N'خورزوق');
INSERT INTO City VALUES (N'اصفهان',N'قهدریجان');
INSERT INTO City VALUES (N'اصفهان',N'شاهین شهر');
INSERT INTO City VALUES (N'اصفهان',N'بهارستان');
INSERT INTO City VALUES (N'اصفهان',N'چمگردان');
INSERT INTO City VALUES (N'اصفهان',N'دهاقان');
INSERT INTO City VALUES (N'اصفهان',N'برف انبار');
INSERT INTO City VALUES (N'اصفهان',N'بادرود');
INSERT INTO City VALUES (N'اصفهان',N'کوهپایه');
INSERT INTO City VALUES (N'اصفهان',N'گلپایگان');
INSERT INTO City VALUES (N'اصفهان',N'عسگران');
INSERT INTO City VALUES (N'اصفهان',N'حنا');
INSERT INTO City VALUES (N'اصفهان',N'کهریزسنگ');
INSERT INTO City VALUES (N'اصفهان',N'مهاباد');
INSERT INTO City VALUES (N'اصفهان',N'کامو و چوگان');
INSERT INTO City VALUES (N'اصفهان',N'افوس');
INSERT INTO City VALUES (N'اصفهان',N'زیباشهر');
INSERT INTO City VALUES (N'اصفهان',N'کوشک');
INSERT INTO City VALUES (N'اصفهان',N'نایین');
INSERT INTO City VALUES (N'اصفهان',N'سین');
INSERT INTO City VALUES (N'اصفهان',N'زازران');
INSERT INTO City VALUES (N'اصفهان',N'مبارکه');
INSERT INTO City VALUES (N'اصفهان',N'ورزنه');
INSERT INTO City VALUES (N'اصفهان',N'ورنامخواست');
INSERT INTO City VALUES (N'اصفهان',N'شاپورآباد');
INSERT INTO City VALUES (N'اصفهان',N'فلاورجان');
INSERT INTO City VALUES (N'اصفهان',N'وزوان');
INSERT INTO City VALUES (N'اصفهان',N'اصفهان');
INSERT INTO City VALUES (N'اصفهان',N'باغ بهادران');
INSERT INTO City VALUES (N'اصفهان',N'چادگان');
INSERT INTO City VALUES (N'اصفهان',N'دامنه');
INSERT INTO City VALUES (N'اصفهان',N'نطنز');
INSERT INTO City VALUES (N'اصفهان',N'محمدآباد');
INSERT INTO City VALUES (N'اصفهان',N'نیاسر');
INSERT INTO City VALUES (N'اصفهان',N'نوش آباد');
INSERT INTO City VALUES (N'اصفهان',N'کمه');
INSERT INTO City VALUES (N'اصفهان',N'جوزدان');
INSERT INTO City VALUES (N'اصفهان',N'قمصر');
INSERT INTO City VALUES (N'اصفهان',N'جندق');
INSERT INTO City VALUES (N'اصفهان',N'طالخونچه');
INSERT INTO City VALUES (N'اصفهان',N'خمینی شهر');
INSERT INTO City VALUES (N'اصفهان',N'باغشاد');
INSERT INTO City VALUES (N'اصفهان',N'دستگرد');
INSERT INTO City VALUES (N'اصفهان',N'ابریشم');
INSERT INTO City VALUES (N'البرز',N'چهارباغ');
INSERT INTO City VALUES (N'البرز',N'آسارا');
INSERT INTO City VALUES (N'البرز',N'کرج');
INSERT INTO City VALUES (N'البرز',N'طالقان');
INSERT INTO City VALUES (N'البرز',N'شهرجدیدهشتگرد');
INSERT INTO City VALUES (N'البرز',N'محمدشهر');
INSERT INTO City VALUES (N'البرز',N'مشکین دشت');
INSERT INTO City VALUES (N'البرز',N'نظرآباد');
INSERT INTO City VALUES (N'البرز',N'هشتگرد');
INSERT INTO City VALUES (N'البرز',N'ماهدشت');
INSERT INTO City VALUES (N'البرز',N'اشتهارد');
INSERT INTO City VALUES (N'البرز',N'کوهسار');
INSERT INTO City VALUES (N'البرز',N'گرمدره');
INSERT INTO City VALUES (N'البرز',N'تنکمان');
INSERT INTO City VALUES (N'البرز',N'گلسار');
INSERT INTO City VALUES (N'البرز',N'کمال شهر');
INSERT INTO City VALUES (N'البرز',N'فردیس');
INSERT INTO City VALUES (N'ایلام',N'آبدانان');
INSERT INTO City VALUES (N'ایلام',N'شباب');
INSERT INTO City VALUES (N'ایلام',N'موسیان');
INSERT INTO City VALUES (N'ایلام',N'بدره');
INSERT INTO City VALUES (N'ایلام',N'ایلام');
INSERT INTO City VALUES (N'ایلام',N'ایوان');
INSERT INTO City VALUES (N'ایلام',N'مهران');
INSERT INTO City VALUES (N'ایلام',N'آسمان آباد');
INSERT INTO City VALUES (N'ایلام',N'پهله');
INSERT INTO City VALUES (N'ایلام',N'مهر');
INSERT INTO City VALUES (N'ایلام',N'سراب باغ');
INSERT INTO City VALUES (N'ایلام',N'بلاوه');
INSERT INTO City VALUES (N'ایلام',N'میمه');
INSERT INTO City VALUES (N'ایلام',N'دره شهر');
INSERT INTO City VALUES (N'ایلام',N'ارکواز');
INSERT INTO City VALUES (N'ایلام',N'مورموری');
INSERT INTO City VALUES (N'ایلام',N'توحید');
INSERT INTO City VALUES (N'ایلام',N'دهلران');
INSERT INTO City VALUES (N'ایلام',N'لومار');
INSERT INTO City VALUES (N'ایلام',N'چوار');
INSERT INTO City VALUES (N'ایلام',N'زرنه');
INSERT INTO City VALUES (N'ایلام',N'صالح آباد');
INSERT INTO City VALUES (N'ایلام',N'سرابله');
INSERT INTO City VALUES (N'ایلام',N'ماژین');
INSERT INTO City VALUES (N'ایلام',N'دلگشا');
INSERT INTO City VALUES (N'بوشهر',N'ریز');
INSERT INTO City VALUES (N'بوشهر',N'برازجان');
INSERT INTO City VALUES (N'بوشهر',N'بندرریگ');
INSERT INTO City VALUES (N'بوشهر',N'اهرم');
INSERT INTO City VALUES (N'بوشهر',N'دوراهک');
INSERT INTO City VALUES (N'بوشهر',N'خورموج');
INSERT INTO City VALUES (N'بوشهر',N'نخل تقی');
INSERT INTO City VALUES (N'بوشهر',N'کلمه');
INSERT INTO City VALUES (N'بوشهر',N'بندردیلم');
INSERT INTO City VALUES (N'بوشهر',N'وحدتیه');
INSERT INTO City VALUES (N'بوشهر',N'بنک');
INSERT INTO City VALUES (N'بوشهر',N'چغادک');
INSERT INTO City VALUES (N'بوشهر',N'بندردیر');
INSERT INTO City VALUES (N'بوشهر',N'کاکی');
INSERT INTO City VALUES (N'بوشهر',N'جم');
INSERT INTO City VALUES (N'بوشهر',N'دالکی');
INSERT INTO City VALUES (N'بوشهر',N'بندرگناوه');
INSERT INTO City VALUES (N'بوشهر',N'آباد');
INSERT INTO City VALUES (N'بوشهر',N'آبدان');
INSERT INTO City VALUES (N'بوشهر',N'خارک');
INSERT INTO City VALUES (N'بوشهر',N'شنبه');
INSERT INTO City VALUES (N'بوشهر',N'بوشکان');
INSERT INTO City VALUES (N'بوشهر',N'انارستان');
INSERT INTO City VALUES (N'بوشهر',N'شبانکاره');
INSERT INTO City VALUES (N'بوشهر',N'سیراف');
INSERT INTO City VALUES (N'بوشهر',N'دلوار');
INSERT INTO City VALUES (N'بوشهر',N'بردستان');
INSERT INTO City VALUES (N'بوشهر',N'بادوله');
INSERT INTO City VALUES (N'بوشهر',N'عسلویه');
INSERT INTO City VALUES (N'بوشهر',N'تنگ ارم');
INSERT INTO City VALUES (N'بوشهر',N'امام حسن');
INSERT INTO City VALUES (N'بوشهر',N'سعد آباد');
INSERT INTO City VALUES (N'بوشهر',N'بندرکنگان');
INSERT INTO City VALUES (N'بوشهر',N'بوشهر');
INSERT INTO City VALUES (N'بوشهر',N'بردخون');
INSERT INTO City VALUES (N'بوشهر',N'آب پخش');
INSERT INTO City VALUES (N'تهران',N'شاهدشهر');
INSERT INTO City VALUES (N'تهران',N'پیشوا');
INSERT INTO City VALUES (N'تهران',N'جوادآباد');
INSERT INTO City VALUES (N'تهران',N'ارجمند');
INSERT INTO City VALUES (N'تهران',N'ری');
INSERT INTO City VALUES (N'تهران',N'نصیرشهر');
INSERT INTO City VALUES (N'تهران',N'رودهن');
INSERT INTO City VALUES (N'تهران',N'اندیشه');
INSERT INTO City VALUES (N'تهران',N'نسیم شهر');
INSERT INTO City VALUES (N'تهران',N'صباشهر');
INSERT INTO City VALUES (N'تهران',N'ملارد');
INSERT INTO City VALUES (N'تهران',N'شمشک');
INSERT INTO City VALUES (N'تهران',N'پاکدشت');
INSERT INTO City VALUES (N'تهران',N'باقرشهر');
INSERT INTO City VALUES (N'تهران',N'احمد آباد مستوفی');
INSERT INTO City VALUES (N'تهران',N'کیلان');
INSERT INTO City VALUES (N'تهران',N'قرچک');
INSERT INTO City VALUES (N'تهران',N'فردوسیه');
INSERT INTO City VALUES (N'تهران',N'گلستان');
INSERT INTO City VALUES (N'تهران',N'ورامین');
INSERT INTO City VALUES (N'تهران',N'فیروزکوه');
INSERT INTO City VALUES (N'تهران',N'فشم');
INSERT INTO City VALUES (N'تهران',N'پرند');
INSERT INTO City VALUES (N'تهران',N'آبعلی');
INSERT INTO City VALUES (N'تهران',N'چهاردانگه');
INSERT INTO City VALUES (N'تهران',N'تهران');
INSERT INTO City VALUES (N'تهران',N'بومهن');
INSERT INTO City VALUES (N'تهران',N'وحیدیه');
INSERT INTO City VALUES (N'تهران',N'صفادشت');
INSERT INTO City VALUES (N'تهران',N'لواسان');
INSERT INTO City VALUES (N'تهران',N'فرون اباد');
INSERT INTO City VALUES (N'تهران',N'کهریزک');
INSERT INTO City VALUES (N'تهران',N'رباطکریم');
INSERT INTO City VALUES (N'تهران',N'آبسرد');
INSERT INTO City VALUES (N'تهران',N'باغستان');
INSERT INTO City VALUES (N'تهران',N'صالحیه');
INSERT INTO City VALUES (N'تهران',N'شهریار');
INSERT INTO City VALUES (N'تهران',N'قدس');
INSERT INTO City VALUES (N'تهران',N'تجریش');
INSERT INTO City VALUES (N'تهران',N'شریف آباد');
INSERT INTO City VALUES (N'تهران',N'حسن آباد');
INSERT INTO City VALUES (N'تهران',N'اسلامشهر');
INSERT INTO City VALUES (N'تهران',N'دماوند');
INSERT INTO City VALUES (N'تهران',N'پردیس');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'وردنجان');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'گوجان');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'گهرو');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'سورشجان');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'سرخون');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'شهرکرد');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'منج');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'بروجن');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'پردنجان');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'سامان');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'فرخ شهر');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'صمصامی');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'طاقانک');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'کاج');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'نقنه');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'لردگان');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'باباحیدر');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'دستنا');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'سودجان');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'بازفت');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'هفشجان');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'سردشت');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'فرادبنه');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'چلیچه');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'بن');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'فارسان');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'شلمزار');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'نافچ');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'دشتک');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'بلداجی');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'آلونی');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'گندمان');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'جونقان');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'ناغان');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'هارونی');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'چلگرد');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'کیان');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'اردل');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'سفیددشت');
INSERT INTO City VALUES (N'چهارمحال و بختیاری',N'مال خلیفه');
INSERT INTO City VALUES (N'خراسان جنوبی',N'اسلامیه');
INSERT INTO City VALUES (N'خراسان جنوبی',N'شوسف');
INSERT INTO City VALUES (N'خراسان جنوبی',N'قاین');
INSERT INTO City VALUES (N'خراسان جنوبی',N'عشق آباد');
INSERT INTO City VALUES (N'خراسان جنوبی',N'طبس مسینا');
INSERT INTO City VALUES (N'خراسان جنوبی',N'ارسک');
INSERT INTO City VALUES (N'خراسان جنوبی',N'آیسک');
INSERT INTO City VALUES (N'خراسان جنوبی',N'نیمبلوک');
INSERT INTO City VALUES (N'خراسان جنوبی',N'دیهوک');
INSERT INTO City VALUES (N'خراسان جنوبی',N'سربیشه');
INSERT INTO City VALUES (N'خراسان جنوبی',N'محمدشهر');
INSERT INTO City VALUES (N'خراسان جنوبی',N'بیرجند');
INSERT INTO City VALUES (N'خراسان جنوبی',N'فردوس');
INSERT INTO City VALUES (N'خراسان جنوبی',N'نهبندان');
INSERT INTO City VALUES (N'خراسان جنوبی',N'اسفدن');
INSERT INTO City VALUES (N'خراسان جنوبی',N'گزیک');
INSERT INTO City VALUES (N'خراسان جنوبی',N'حاجی آباد');
INSERT INTO City VALUES (N'خراسان جنوبی',N'سه قلعه');
INSERT INTO City VALUES (N'خراسان جنوبی',N'آرین شهر');
INSERT INTO City VALUES (N'خراسان جنوبی',N'مود');
INSERT INTO City VALUES (N'خراسان جنوبی',N'خوسف');
INSERT INTO City VALUES (N'خراسان جنوبی',N'قهستان');
INSERT INTO City VALUES (N'خراسان جنوبی',N'بشرویه');
INSERT INTO City VALUES (N'خراسان جنوبی',N'سرایان');
INSERT INTO City VALUES (N'خراسان جنوبی',N'خضری دشت بیاض');
INSERT INTO City VALUES (N'خراسان جنوبی',N'طبس');
INSERT INTO City VALUES (N'خراسان جنوبی',N'اسدیه');
INSERT INTO City VALUES (N'خراسان جنوبی',N'زهان');
INSERT INTO City VALUES (N'خراسان رضوی',N'بار');
INSERT INTO City VALUES (N'خراسان رضوی',N'نیل شهر');
INSERT INTO City VALUES (N'خراسان رضوی',N'جنگل');
INSERT INTO City VALUES (N'خراسان رضوی',N'درود');
INSERT INTO City VALUES (N'خراسان رضوی',N'رباط سنگ');
INSERT INTO City VALUES (N'خراسان رضوی',N'سلطان آباد');
INSERT INTO City VALUES (N'خراسان رضوی',N'فریمان');
INSERT INTO City VALUES (N'خراسان رضوی',N'گناباد');
INSERT INTO City VALUES (N'خراسان رضوی',N'کاریز');
INSERT INTO City VALUES (N'خراسان رضوی',N'همت آباد');
INSERT INTO City VALUES (N'خراسان رضوی',N'سلامی');
INSERT INTO City VALUES (N'خراسان رضوی',N'باجگیران');
INSERT INTO City VALUES (N'خراسان رضوی',N'بجستان');
INSERT INTO City VALUES (N'خراسان رضوی',N'چناران');
INSERT INTO City VALUES (N'خراسان رضوی',N'درگز');
INSERT INTO City VALUES (N'خراسان رضوی',N'کلات');
INSERT INTO City VALUES (N'خراسان رضوی',N'چکنه');
INSERT INTO City VALUES (N'خراسان رضوی',N'نصرآباد');
INSERT INTO City VALUES (N'خراسان رضوی',N'بردسکن');
INSERT INTO City VALUES (N'خراسان رضوی',N'مشهد');
INSERT INTO City VALUES (N'خراسان رضوی',N'کدکن');
INSERT INTO City VALUES (N'خراسان رضوی',N'نقاب');
INSERT INTO City VALUES (N'خراسان رضوی',N'قلندرآباد');
INSERT INTO City VALUES (N'خراسان رضوی',N'کاشمر');
INSERT INTO City VALUES (N'خراسان رضوی',N'شاندیز');
INSERT INTO City VALUES (N'خراسان رضوی',N'نشتیفان');
INSERT INTO City VALUES (N'خراسان رضوی',N'ششتمد');
INSERT INTO City VALUES (N'خراسان رضوی',N'شادمهر');
INSERT INTO City VALUES (N'خراسان رضوی',N'عشق آباد');
INSERT INTO City VALUES (N'خراسان رضوی',N'چاپشلو');
INSERT INTO City VALUES (N'خراسان رضوی',N'رشتخوار');
INSERT INTO City VALUES (N'خراسان رضوی',N'قدمگاه');
INSERT INTO City VALUES (N'خراسان رضوی',N'صالح آباد');
INSERT INTO City VALUES (N'خراسان رضوی',N'داورزن');
INSERT INTO City VALUES (N'خراسان رضوی',N'فرهادگرد');
INSERT INTO City VALUES (N'خراسان رضوی',N'کاخک');
INSERT INTO City VALUES (N'خراسان رضوی',N'مشهدریزه');
INSERT INTO City VALUES (N'خراسان رضوی',N'جغتای');
INSERT INTO City VALUES (N'خراسان رضوی',N'مزدآوند');
INSERT INTO City VALUES (N'خراسان رضوی',N'قوچان');
INSERT INTO City VALUES (N'خراسان رضوی',N'یونسی');
INSERT INTO City VALUES (N'خراسان رضوی',N'سنگان');
INSERT INTO City VALUES (N'خراسان رضوی',N'نوخندان');
INSERT INTO City VALUES (N'خراسان رضوی',N'کندر');
INSERT INTO City VALUES (N'خراسان رضوی',N'نیشابور');
INSERT INTO City VALUES (N'خراسان رضوی',N'احمدابادصولت');
INSERT INTO City VALUES (N'خراسان رضوی',N'شهراباد');
INSERT INTO City VALUES (N'خراسان رضوی',N'رضویه');
INSERT INTO City VALUES (N'خراسان رضوی',N'تربت حیدریه');
INSERT INTO City VALUES (N'خراسان رضوی',N'باخرز');
INSERT INTO City VALUES (N'خراسان رضوی',N'سفیدسنگ');
INSERT INTO City VALUES (N'خراسان رضوی',N'بیدخت');
INSERT INTO City VALUES (N'خراسان رضوی',N'تایباد');
INSERT INTO City VALUES (N'خراسان رضوی',N'فیروزه');
INSERT INTO City VALUES (N'خراسان رضوی',N'قاسم آباد');
INSERT INTO City VALUES (N'خراسان رضوی',N'سبزوار');
INSERT INTO City VALUES (N'خراسان رضوی',N'فیض آباد');
INSERT INTO City VALUES (N'خراسان رضوی',N'گلمکان');
INSERT INTO City VALUES (N'خراسان رضوی',N'لطف آباد');
INSERT INTO City VALUES (N'خراسان رضوی',N'شهرزو');
INSERT INTO City VALUES (N'خراسان رضوی',N'خرو');
INSERT INTO City VALUES (N'خراسان رضوی',N'تربت جام');
INSERT INTO City VALUES (N'خراسان رضوی',N'انابد');
INSERT INTO City VALUES (N'خراسان رضوی',N'ملک آباد');
INSERT INTO City VALUES (N'خراسان رضوی',N'بایک');
INSERT INTO City VALUES (N'خراسان رضوی',N'دولت آباد');
INSERT INTO City VALUES (N'خراسان رضوی',N'سرخس');
INSERT INTO City VALUES (N'خراسان رضوی',N'ریوش');
INSERT INTO City VALUES (N'خراسان رضوی',N'طرقبه');
INSERT INTO City VALUES (N'خراسان رضوی',N'خواف');
INSERT INTO City VALUES (N'خراسان رضوی',N'روداب');
INSERT INTO City VALUES (N'خراسان رضوی',N'خلیل آباد');
INSERT INTO City VALUES (N'خراسان شمالی',N'چناران شهر');
INSERT INTO City VALUES (N'خراسان شمالی',N'راز');
INSERT INTO City VALUES (N'خراسان شمالی',N'پیش قلعه');
INSERT INTO City VALUES (N'خراسان شمالی',N'قوشخانه');
INSERT INTO City VALUES (N'خراسان شمالی',N'شوقان');
INSERT INTO City VALUES (N'خراسان شمالی',N'اسفراین');
INSERT INTO City VALUES (N'خراسان شمالی',N'گرمه');
INSERT INTO City VALUES (N'خراسان شمالی',N'قاضی');
INSERT INTO City VALUES (N'خراسان شمالی',N'شیروان');
INSERT INTO City VALUES (N'خراسان شمالی',N'حصارگرمخان');
INSERT INTO City VALUES (N'خراسان شمالی',N'آشخانه');
INSERT INTO City VALUES (N'خراسان شمالی',N'تیتکانلو');
INSERT INTO City VALUES (N'خراسان شمالی',N'جاجرم');
INSERT INTO City VALUES (N'خراسان شمالی',N'بجنورد');
INSERT INTO City VALUES (N'خراسان شمالی',N'درق');
INSERT INTO City VALUES (N'خراسان شمالی',N'آوا');
INSERT INTO City VALUES (N'خراسان شمالی',N'زیارت');
INSERT INTO City VALUES (N'خراسان شمالی',N'سنخواست');
INSERT INTO City VALUES (N'خراسان شمالی',N'صفی آباد');
INSERT INTO City VALUES (N'خراسان شمالی',N'ایور');
INSERT INTO City VALUES (N'خراسان شمالی',N'فاروج');
INSERT INTO City VALUES (N'خراسان شمالی',N'لوجلی');
INSERT INTO City VALUES (N'خوزستان',N'هفتگل');
INSERT INTO City VALUES (N'خوزستان',N'بیدروبه');
INSERT INTO City VALUES (N'خوزستان',N'شاوور');
INSERT INTO City VALUES (N'خوزستان',N'حمزه');
INSERT INTO City VALUES (N'خوزستان',N'گتوند');
INSERT INTO City VALUES (N'خوزستان',N'شرافت');
INSERT INTO City VALUES (N'خوزستان',N'منصوریه');
INSERT INTO City VALUES (N'خوزستان',N'زهره');
INSERT INTO City VALUES (N'خوزستان',N'رامهرمز');
INSERT INTO City VALUES (N'خوزستان',N'بندرامام خمینی');
INSERT INTO City VALUES (N'خوزستان',N'کوت عبداله');
INSERT INTO City VALUES (N'خوزستان',N'میداود');
INSERT INTO City VALUES (N'خوزستان',N'چغامیش');
INSERT INTO City VALUES (N'خوزستان',N'ملاثانی');
INSERT INTO City VALUES (N'خوزستان',N'چم گلک');
INSERT INTO City VALUES (N'خوزستان',N'حر');
INSERT INTO City VALUES (N'خوزستان',N'شمس آباد');
INSERT INTO City VALUES (N'خوزستان',N'آبژدان');
INSERT INTO City VALUES (N'خوزستان',N'چویبده');
INSERT INTO City VALUES (N'خوزستان',N'مسجدسلیمان');
INSERT INTO City VALUES (N'خوزستان',N'مقاومت');
INSERT INTO City VALUES (N'خوزستان',N'ترکالکی');
INSERT INTO City VALUES (N'خوزستان',N'دارخوین');
INSERT INTO City VALUES (N'خوزستان',N'سردشت');
INSERT INTO City VALUES (N'خوزستان',N'لالی');
INSERT INTO City VALUES (N'خوزستان',N'کوت سیدنعیم');
INSERT INTO City VALUES (N'خوزستان',N'حمیدیه');
INSERT INTO City VALUES (N'خوزستان',N'دهدز');
INSERT INTO City VALUES (N'خوزستان',N'قلعه تل');
INSERT INTO City VALUES (N'خوزستان',N'میانرود');
INSERT INTO City VALUES (N'خوزستان',N'رفیع');
INSERT INTO City VALUES (N'خوزستان',N'اندیمشک');
INSERT INTO City VALUES (N'خوزستان',N'الوان');
INSERT INTO City VALUES (N'خوزستان',N'سالند');
INSERT INTO City VALUES (N'خوزستان',N'صالح شهر');
INSERT INTO City VALUES (N'خوزستان',N'اروندکنار');
INSERT INTO City VALUES (N'خوزستان',N'سرداران');
INSERT INTO City VALUES (N'خوزستان',N'تشان');
INSERT INTO City VALUES (N'خوزستان',N'رامشیر');
INSERT INTO City VALUES (N'خوزستان',N'شادگان');
INSERT INTO City VALUES (N'خوزستان',N'بندرماهشهر');
INSERT INTO City VALUES (N'خوزستان',N'جایزان');
INSERT INTO City VALUES (N'خوزستان',N'بستان');
INSERT INTO City VALUES (N'خوزستان',N'ویس');
INSERT INTO City VALUES (N'خوزستان',N'اهواز');
INSERT INTO City VALUES (N'خوزستان',N'فتح المبین');
INSERT INTO City VALUES (N'خوزستان',N'شهر امام');
INSERT INTO City VALUES (N'خوزستان',N'قلعه خواجه');
INSERT INTO City VALUES (N'خوزستان',N'حسینیه');
INSERT INTO City VALUES (N'خوزستان',N'گلگیر');
INSERT INTO City VALUES (N'خوزستان',N'مینوشهر');
INSERT INTO City VALUES (N'خوزستان',N'سماله');
INSERT INTO City VALUES (N'خوزستان',N'شوشتر');
INSERT INTO City VALUES (N'خوزستان',N'بهبهان');
INSERT INTO City VALUES (N'خوزستان',N'هندیجان');
INSERT INTO City VALUES (N'خوزستان',N'ابوحمیظه');
INSERT INTO City VALUES (N'خوزستان',N'آغاجاری');
INSERT INTO City VALUES (N'خوزستان',N'ایذه');
INSERT INTO City VALUES (N'خوزستان',N'صیدون');
INSERT INTO City VALUES (N'خوزستان',N'سیاه منصور');
INSERT INTO City VALUES (N'خوزستان',N'هویزه');
INSERT INTO City VALUES (N'خوزستان',N'آزادی');
INSERT INTO City VALUES (N'خوزستان',N'شوش');
INSERT INTO City VALUES (N'خوزستان',N'دزفول');
INSERT INTO City VALUES (N'خوزستان',N'جنت مکان');
INSERT INTO City VALUES (N'خوزستان',N'آبادان');
INSERT INTO City VALUES (N'خوزستان',N'گوریه');
INSERT INTO City VALUES (N'خوزستان',N'خرمشهر');
INSERT INTO City VALUES (N'خوزستان',N'مشراگه');
INSERT INTO City VALUES (N'خوزستان',N'خنافره');
INSERT INTO City VALUES (N'خوزستان',N'چمران');
INSERT INTO City VALUES (N'خوزستان',N'امیدیه');
INSERT INTO City VALUES (N'خوزستان',N'سوسنگرد');
INSERT INTO City VALUES (N'خوزستان',N'شیبان');
INSERT INTO City VALUES (N'خوزستان',N'الهایی');
INSERT INTO City VALUES (N'خوزستان',N'باغ ملک');
INSERT INTO City VALUES (N'خوزستان',N'صفی آباد');
INSERT INTO City VALUES (N'زنجان',N'سجاس');
INSERT INTO City VALUES (N'زنجان',N'زرین رود');
INSERT INTO City VALUES (N'زنجان',N'آب بر');
INSERT INTO City VALUES (N'زنجان',N'ارمغانخانه');
INSERT INTO City VALUES (N'زنجان',N'کرسف');
INSERT INTO City VALUES (N'زنجان',N'هیدج');
INSERT INTO City VALUES (N'زنجان',N'سلطانیه');
INSERT INTO City VALUES (N'زنجان',N'خرمدره');
INSERT INTO City VALUES (N'زنجان',N'نیک پی');
INSERT INTO City VALUES (N'زنجان',N'قیدار');
INSERT INTO City VALUES (N'زنجان',N'ابهر');
INSERT INTO City VALUES (N'زنجان',N'دندی');
INSERT INTO City VALUES (N'زنجان',N'حلب');
INSERT INTO City VALUES (N'زنجان',N'نوربهار');
INSERT INTO City VALUES (N'زنجان',N'گرماب');
INSERT INTO City VALUES (N'زنجان',N'چورزق');
INSERT INTO City VALUES (N'زنجان',N'زنجان');
INSERT INTO City VALUES (N'زنجان',N'سهرورد');
INSERT INTO City VALUES (N'زنجان',N'صایین قلعه');
INSERT INTO City VALUES (N'زنجان',N'ماه نشان');
INSERT INTO City VALUES (N'زنجان',N'زرین آباد');
INSERT INTO City VALUES (N'سمنان',N'ایوانکی');
INSERT INTO City VALUES (N'سمنان',N'مجن');
INSERT INTO City VALUES (N'سمنان',N'دامغان');
INSERT INTO City VALUES (N'سمنان',N'سرخه');
INSERT INTO City VALUES (N'سمنان',N'مهدی شهر');
INSERT INTO City VALUES (N'سمنان',N'شاهرود');
INSERT INTO City VALUES (N'سمنان',N'سمنان');
INSERT INTO City VALUES (N'سمنان',N'کهن آباد');
INSERT INTO City VALUES (N'سمنان',N'گرمسار');
INSERT INTO City VALUES (N'سمنان',N'کلاته خیج');
INSERT INTO City VALUES (N'سمنان',N'دیباج');
INSERT INTO City VALUES (N'سمنان',N'درجزین');
INSERT INTO City VALUES (N'سمنان',N'رودیان');
INSERT INTO City VALUES (N'سمنان',N'بسطام');
INSERT INTO City VALUES (N'سمنان',N'امیریه');
INSERT INTO City VALUES (N'سمنان',N'میامی');
INSERT INTO City VALUES (N'سمنان',N'شهمیرزاد');
INSERT INTO City VALUES (N'سمنان',N'بیارجمند');
INSERT INTO City VALUES (N'سمنان',N'کلاته');
INSERT INTO City VALUES (N'سمنان',N'آرادان');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'محمدی');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'شهرک علی اکبر');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'بنجار');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'گلمورتی');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'نگور');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'راسک');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'بنت');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'قصرقند');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'جالق');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'هیدوچ');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'نوک آباد');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'زهک');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'بمپور');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'پیشین');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'گشت');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'محمدآباد');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'زاهدان');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'زابلی');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'چاه بهار');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'زرآباد');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'بزمان');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'اسپکه');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'فنوج');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'سراوان');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'ادیمی');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'زابل');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'دوست محمد');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'ایرانشهر');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'سرباز');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'سیرکان');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'میرجاوه');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'نصرت آباد');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'سوران');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'خاش');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'کنارک');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'محمدان');
INSERT INTO City VALUES (N'سیستان و بلوچستان',N'نیک شهر');
INSERT INTO City VALUES (N'فارس',N'کازرون');
INSERT INTO City VALUES (N'فارس',N'کارزین (فتح آباد)');
INSERT INTO City VALUES (N'فارس',N'فدامی');
INSERT INTO City VALUES (N'فارس',N'خومه زار');
INSERT INTO City VALUES (N'فارس',N'سلطان شهر');
INSERT INTO City VALUES (N'فارس',N'فیروزآباد');
INSERT INTO City VALUES (N'فارس',N'دبیران');
INSERT INTO City VALUES (N'فارس',N'باب انار');
INSERT INTO City VALUES (N'فارس',N'رامجرد');
INSERT INTO City VALUES (N'فارس',N'سروستان');
INSERT INTO City VALUES (N'فارس',N'قره بلاغ');
INSERT INTO City VALUES (N'فارس',N'ارسنجان');
INSERT INTO City VALUES (N'فارس',N'دژکرد');
INSERT INTO City VALUES (N'فارس',N'بیرم');
INSERT INTO City VALUES (N'فارس',N'دهرم');
INSERT INTO City VALUES (N'فارس',N'شیراز');
INSERT INTO City VALUES (N'فارس',N'ایزدخواست');
INSERT INTO City VALUES (N'فارس',N'علامرودشت');
INSERT INTO City VALUES (N'فارس',N'اوز');
INSERT INTO City VALUES (N'فارس',N'وراوی');
INSERT INTO City VALUES (N'فارس',N'بیضا');
INSERT INTO City VALUES (N'فارس',N'نی ریز');
INSERT INTO City VALUES (N'فارس',N'کنارتخته');
INSERT INTO City VALUES (N'فارس',N'امام شهر');
INSERT INTO City VALUES (N'فارس',N'جهرم');
INSERT INTO City VALUES (N'فارس',N'بابامنیر');
INSERT INTO City VALUES (N'فارس',N'گراش');
INSERT INTO City VALUES (N'فارس',N'فسا');
INSERT INTO City VALUES (N'فارس',N'شهرپیر');
INSERT INTO City VALUES (N'فارس',N'حسن اباد');
INSERT INTO City VALUES (N'فارس',N'کامفیروز');
INSERT INTO City VALUES (N'فارس',N'خنج');
INSERT INTO City VALUES (N'فارس',N'خانه زنیان');
INSERT INTO City VALUES (N'فارس',N'استهبان');
INSERT INTO City VALUES (N'فارس',N'بوانات');
INSERT INTO City VALUES (N'فارس',N'لطیفی');
INSERT INTO City VALUES (N'فارس',N'فراشبند');
INSERT INTO City VALUES (N'فارس',N'زرقان');
INSERT INTO City VALUES (N'فارس',N'صغاد');
INSERT INTO City VALUES (N'فارس',N'اشکنان');
INSERT INTO City VALUES (N'فارس',N'قایمیه');
INSERT INTO City VALUES (N'فارس',N'گله دار');
INSERT INTO City VALUES (N'فارس',N'دوبرجی');
INSERT INTO City VALUES (N'فارس',N'آباده طشک');
INSERT INTO City VALUES (N'فارس',N'خرامه');
INSERT INTO City VALUES (N'فارس',N'میمند');
INSERT INTO City VALUES (N'فارس',N'افزر');
INSERT INTO City VALUES (N'فارس',N'دوزه');
INSERT INTO City VALUES (N'فارس',N'سیدان');
INSERT INTO City VALUES (N'فارس',N'کوپن');
INSERT INTO City VALUES (N'فارس',N'زاهدشهر');
INSERT INTO City VALUES (N'فارس',N'قادراباد');
INSERT INTO City VALUES (N'فارس',N'سده');
INSERT INTO City VALUES (N'فارس',N'بنارویه');
INSERT INTO City VALUES (N'فارس',N'سعادت شهر');
INSERT INTO City VALUES (N'فارس',N'شهرصدرا');
INSERT INTO City VALUES (N'فارس',N'سورمق');
INSERT INTO City VALUES (N'فارس',N'حسامی');
INSERT INTO City VALUES (N'فارس',N'جویم');
INSERT INTO City VALUES (N'فارس',N'خوزی');
INSERT INTO City VALUES (N'فارس',N'اردکان');
INSERT INTO City VALUES (N'فارس',N'قطرویه');
INSERT INTO City VALUES (N'فارس',N'نودان');
INSERT INTO City VALUES (N'فارس',N'مبارک آباددیز');
INSERT INTO City VALUES (N'فارس',N'داراب');
INSERT INTO City VALUES (N'فارس',N'نورآباد');
INSERT INTO City VALUES (N'فارس',N'کوار');
INSERT INTO City VALUES (N'فارس',N'نوبندگان');
INSERT INTO City VALUES (N'فارس',N'حاجی آباد');
INSERT INTO City VALUES (N'فارس',N'خاوران');
INSERT INTO City VALUES (N'فارس',N'مرودشت');
INSERT INTO City VALUES (N'فارس',N'کوهنجان');
INSERT INTO City VALUES (N'فارس',N'ششده');
INSERT INTO City VALUES (N'فارس',N'مزایجان');
INSERT INTO City VALUES (N'فارس',N'ایج');
INSERT INTO City VALUES (N'فارس',N'خور');
INSERT INTO City VALUES (N'فارس',N'نوجین');
INSERT INTO City VALUES (N'فارس',N'لپویی');
INSERT INTO City VALUES (N'فارس',N'بهمن');
INSERT INTO City VALUES (N'فارس',N'اهل');
INSERT INTO City VALUES (N'فارس',N'خشت');
INSERT INTO City VALUES (N'فارس',N'مهر');
INSERT INTO City VALUES (N'فارس',N'جنت شهر');
INSERT INTO City VALUES (N'فارس',N'مشکان');
INSERT INTO City VALUES (N'فارس',N'بالاده');
INSERT INTO City VALUES (N'فارس',N'قیر');
INSERT INTO City VALUES (N'فارس',N'قطب آباد');
INSERT INTO City VALUES (N'فارس',N'خانیمن');
INSERT INTO City VALUES (N'فارس',N'مصیری');
INSERT INTO City VALUES (N'فارس',N'میانشهر');
INSERT INTO City VALUES (N'فارس',N'صفاشهر');
INSERT INTO City VALUES (N'فارس',N'اقلید');
INSERT INTO City VALUES (N'فارس',N'عمادده');
INSERT INTO City VALUES (N'فارس',N'مادرسلیمان');
INSERT INTO City VALUES (N'فارس',N'داریان');
INSERT INTO City VALUES (N'فارس',N'رونیز');
INSERT INTO City VALUES (N'فارس',N'کره ای');
INSERT INTO City VALUES (N'فارس',N'لار');
INSERT INTO City VALUES (N'فارس',N'اسیر');
INSERT INTO City VALUES (N'فارس',N'هماشهر');
INSERT INTO City VALUES (N'فارس',N'آباده');
INSERT INTO City VALUES (N'فارس',N'لامرد');
INSERT INTO City VALUES (N'قزوین',N'سگزآباد');
INSERT INTO City VALUES (N'قزوین',N'بیدستان');
INSERT INTO City VALUES (N'قزوین',N'کوهین');
INSERT INTO City VALUES (N'قزوین',N'رازمیان');
INSERT INTO City VALUES (N'قزوین',N'خرمدشت');
INSERT INTO City VALUES (N'قزوین',N'آبگرم');
INSERT INTO City VALUES (N'قزوین',N'شال');
INSERT INTO City VALUES (N'قزوین',N'شریفیه');
INSERT INTO City VALUES (N'قزوین',N'اقبالیه');
INSERT INTO City VALUES (N'قزوین',N'نرجه');
INSERT INTO City VALUES (N'قزوین',N'ارداق');
INSERT INTO City VALUES (N'قزوین',N'الوند');
INSERT INTO City VALUES (N'قزوین',N'خاکعلی');
INSERT INTO City VALUES (N'قزوین',N'سیردان');
INSERT INTO City VALUES (N'قزوین',N'ضیاڈآباد');
INSERT INTO City VALUES (N'قزوین',N'بویین زهرا');
INSERT INTO City VALUES (N'قزوین',N'محمدیه');
INSERT INTO City VALUES (N'قزوین',N'محمودآبادنمونه');
INSERT INTO City VALUES (N'قزوین',N'معلم کلایه');
INSERT INTO City VALUES (N'قزوین',N'اسفرورین');
INSERT INTO City VALUES (N'قزوین',N'آوج');
INSERT INTO City VALUES (N'قزوین',N'دانسفهان');
INSERT INTO City VALUES (N'قزوین',N'آبیک');
INSERT INTO City VALUES (N'قزوین',N'قزوین');
INSERT INTO City VALUES (N'قزوین',N'تاکستان');
INSERT INTO City VALUES (N'قم',N'کهک');
INSERT INTO City VALUES (N'قم',N'قم');
INSERT INTO City VALUES (N'قم',N'سلفچگان');
INSERT INTO City VALUES (N'قم',N'جعفریه');
INSERT INTO City VALUES (N'قم',N'قنوات');
INSERT INTO City VALUES (N'قم',N'دستجرد');
INSERT INTO City VALUES (N'کردستان',N'قروه');
INSERT INTO City VALUES (N'کردستان',N'توپ آغاج');
INSERT INTO City VALUES (N'کردستان',N'سروآباد');
INSERT INTO City VALUES (N'کردستان',N'بویین سفلی');
INSERT INTO City VALUES (N'کردستان',N'زرینه');
INSERT INTO City VALUES (N'کردستان',N'دلبران');
INSERT INTO City VALUES (N'کردستان',N'سنندج');
INSERT INTO City VALUES (N'کردستان',N'یاسوکند');
INSERT INTO City VALUES (N'کردستان',N'موچش');
INSERT INTO City VALUES (N'کردستان',N'بانه');
INSERT INTO City VALUES (N'کردستان',N'مریوان');
INSERT INTO City VALUES (N'کردستان',N'سریش آباد');
INSERT INTO City VALUES (N'کردستان',N'صاحب');
INSERT INTO City VALUES (N'کردستان',N'دهگلان');
INSERT INTO City VALUES (N'کردستان',N'بابارشانی');
INSERT INTO City VALUES (N'کردستان',N'دیواندره');
INSERT INTO City VALUES (N'کردستان',N'برده رشه');
INSERT INTO City VALUES (N'کردستان',N'شویشه');
INSERT INTO City VALUES (N'کردستان',N'بیجار');
INSERT INTO City VALUES (N'کردستان',N'اورامان تخت');
INSERT INTO City VALUES (N'کردستان',N'کانی سور');
INSERT INTO City VALUES (N'کردستان',N'کانی دینار');
INSERT INTO City VALUES (N'کردستان',N'دزج');
INSERT INTO City VALUES (N'کردستان',N'سقز');
INSERT INTO City VALUES (N'کردستان',N'بلبان آباد');
INSERT INTO City VALUES (N'کردستان',N'پیرتاج');
INSERT INTO City VALUES (N'کردستان',N'کامیاران');
INSERT INTO City VALUES (N'کردستان',N'آرمرده');
INSERT INTO City VALUES (N'کردستان',N'چناره');
INSERT INTO City VALUES (N'کرمان',N'کهنوج');
INSERT INTO City VALUES (N'کرمان',N'بلوک');
INSERT INTO City VALUES (N'کرمان',N'پاریز');
INSERT INTO City VALUES (N'کرمان',N'گنبکی');
INSERT INTO City VALUES (N'کرمان',N'زنگی آباد');
INSERT INTO City VALUES (N'کرمان',N'بم');
INSERT INTO City VALUES (N'کرمان',N'خانوک');
INSERT INTO City VALUES (N'کرمان',N'کیانشهر');
INSERT INTO City VALUES (N'کرمان',N'جوپار');
INSERT INTO City VALUES (N'کرمان',N'عنبرآباد');
INSERT INTO City VALUES (N'کرمان',N'جوزم');
INSERT INTO City VALUES (N'کرمان',N'نظام شهر');
INSERT INTO City VALUES (N'کرمان',N'لاله زار');
INSERT INTO City VALUES (N'کرمان',N'کشکوییه');
INSERT INTO City VALUES (N'کرمان',N'زیدآباد');
INSERT INTO City VALUES (N'کرمان',N'هنزا');
INSERT INTO City VALUES (N'کرمان',N'چترود');
INSERT INTO City VALUES (N'کرمان',N'جبالبارز');
INSERT INTO City VALUES (N'کرمان',N'سیرجان');
INSERT INTO City VALUES (N'کرمان',N'رودبار');
INSERT INTO City VALUES (N'کرمان',N'کرمان');
INSERT INTO City VALUES (N'کرمان',N'بافت');
INSERT INTO City VALUES (N'کرمان',N'صفاییه');
INSERT INTO City VALUES (N'کرمان',N'منوجان');
INSERT INTO City VALUES (N'کرمان',N'اندوهجرد');
INSERT INTO City VALUES (N'کرمان',N'هجدک');
INSERT INTO City VALUES (N'کرمان',N'خورسند');
INSERT INTO City VALUES (N'کرمان',N'امین شهر');
INSERT INTO City VALUES (N'کرمان',N'بردسیر');
INSERT INTO City VALUES (N'کرمان',N'رفسنجان');
INSERT INTO City VALUES (N'کرمان',N'هماشهر');
INSERT INTO City VALUES (N'کرمان',N'محمدآباد');
INSERT INTO City VALUES (N'کرمان',N'اختیارآباد');
INSERT INTO City VALUES (N'کرمان',N'بروات');
INSERT INTO City VALUES (N'کرمان',N'ریحان');
INSERT INTO City VALUES (N'کرمان',N'کوهبنان');
INSERT INTO City VALUES (N'کرمان',N'ماهان');
INSERT INTO City VALUES (N'کرمان',N'دوساری');
INSERT INTO City VALUES (N'کرمان',N'دهج');
INSERT INTO City VALUES (N'کرمان',N'فاریاب');
INSERT INTO City VALUES (N'کرمان',N'گلزار');
INSERT INTO City VALUES (N'کرمان',N'بهرمان');
INSERT INTO City VALUES (N'کرمان',N'بلورد');
INSERT INTO City VALUES (N'کرمان',N'فهرج');
INSERT INTO City VALUES (N'کرمان',N'کاظم آباد');
INSERT INTO City VALUES (N'کرمان',N'جیرفت');
INSERT INTO City VALUES (N'کرمان',N'نجف شهر');
INSERT INTO City VALUES (N'کرمان',N'قلعه گنج');
INSERT INTO City VALUES (N'کرمان',N'باغین');
INSERT INTO City VALUES (N'کرمان',N'بزنجان');
INSERT INTO City VALUES (N'کرمان',N'زرند');
INSERT INTO City VALUES (N'کرمان',N'نودژ');
INSERT INTO City VALUES (N'کرمان',N'گلباف');
INSERT INTO City VALUES (N'کرمان',N'راور');
INSERT INTO City VALUES (N'کرمان',N'خاتون اباد');
INSERT INTO City VALUES (N'کرمان',N'نرماشیر');
INSERT INTO City VALUES (N'کرمان',N'دشتکار');
INSERT INTO City VALUES (N'کرمان',N'مس سرچشمه');
INSERT INTO City VALUES (N'کرمان',N'خواجو شهر');
INSERT INTO City VALUES (N'کرمان',N'رابر');
INSERT INTO City VALUES (N'کرمان',N'راین');
INSERT INTO City VALUES (N'کرمان',N'درب بهشت');
INSERT INTO City VALUES (N'کرمان',N'یزدان شهر');
INSERT INTO City VALUES (N'کرمان',N'زهکلوت');
INSERT INTO City VALUES (N'کرمان',N'محی آباد');
INSERT INTO City VALUES (N'کرمان',N'مردهک');
INSERT INTO City VALUES (N'کرمان',N'شهداد');
INSERT INTO City VALUES (N'کرمان',N'ارزوییه');
INSERT INTO City VALUES (N'کرمان',N'نگار');
INSERT INTO City VALUES (N'کرمان',N'شهربابک');
INSERT INTO City VALUES (N'کرمان',N'انار');
INSERT INTO City VALUES (N'کرمانشاه',N'سنقر');
INSERT INTO City VALUES (N'کرمانشاه',N'شاهو');
INSERT INTO City VALUES (N'کرمانشاه',N'بانوره');
INSERT INTO City VALUES (N'کرمانشاه',N'تازه آباد');
INSERT INTO City VALUES (N'کرمانشاه',N'هلشی');
INSERT INTO City VALUES (N'کرمانشاه',N'جوانرود');
INSERT INTO City VALUES (N'کرمانشاه',N'قصرشیرین');
INSERT INTO City VALUES (N'کرمانشاه',N'نوسود');
INSERT INTO City VALUES (N'کرمانشاه',N'کرند');
INSERT INTO City VALUES (N'کرمانشاه',N'کوزران');
INSERT INTO City VALUES (N'کرمانشاه',N'بیستون');
INSERT INTO City VALUES (N'کرمانشاه',N'حمیل');
INSERT INTO City VALUES (N'کرمانشاه',N'گیلانغرب');
INSERT INTO City VALUES (N'کرمانشاه',N'سطر');
INSERT INTO City VALUES (N'کرمانشاه',N'روانسر');
INSERT INTO City VALUES (N'کرمانشاه',N'پاوه');
INSERT INTO City VALUES (N'کرمانشاه',N'ازگله');
INSERT INTO City VALUES (N'کرمانشاه',N'کرمانشاه');
INSERT INTO City VALUES (N'کرمانشاه',N'میان راهان');
INSERT INTO City VALUES (N'کرمانشاه',N'کنگاور');
INSERT INTO City VALUES (N'کرمانشاه',N'سرپل ذهاب');
INSERT INTO City VALUES (N'کرمانشاه',N'ریجاب');
INSERT INTO City VALUES (N'کرمانشاه',N'باینگان');
INSERT INTO City VALUES (N'کرمانشاه',N'هرسین');
INSERT INTO City VALUES (N'کرمانشاه',N'اسلام آبادغرب');
INSERT INTO City VALUES (N'کرمانشاه',N'سرمست');
INSERT INTO City VALUES (N'کرمانشاه',N'سومار');
INSERT INTO City VALUES (N'کرمانشاه',N'نودشه');
INSERT INTO City VALUES (N'کرمانشاه',N'گهواره');
INSERT INTO City VALUES (N'کرمانشاه',N'رباط');
INSERT INTO City VALUES (N'کرمانشاه',N'صحنه');
INSERT INTO City VALUES (N'کرمانشاه',N'گودین');
INSERT INTO City VALUES (N'کهگیلویه وبویراحمد',N'گراب سفلی');
INSERT INTO City VALUES (N'کهگیلویه وبویراحمد',N'لنده');
INSERT INTO City VALUES (N'کهگیلویه وبویراحمد',N'سی سخت');
INSERT INTO City VALUES (N'کهگیلویه وبویراحمد',N'دهدشت');
INSERT INTO City VALUES (N'کهگیلویه وبویراحمد',N'یاسوج');
INSERT INTO City VALUES (N'کهگیلویه وبویراحمد',N'سرفاریاب');
INSERT INTO City VALUES (N'کهگیلویه وبویراحمد',N'دوگنبدان');
INSERT INTO City VALUES (N'کهگیلویه وبویراحمد',N'چیتاب');
INSERT INTO City VALUES (N'کهگیلویه وبویراحمد',N'لیکک');
INSERT INTO City VALUES (N'کهگیلویه وبویراحمد',N'دیشموک');
INSERT INTO City VALUES (N'کهگیلویه وبویراحمد',N'مادوان');
INSERT INTO City VALUES (N'کهگیلویه وبویراحمد',N'باشت');
INSERT INTO City VALUES (N'کهگیلویه وبویراحمد',N'پاتاوه');
INSERT INTO City VALUES (N'کهگیلویه وبویراحمد',N'قلعه رییسی');
INSERT INTO City VALUES (N'کهگیلویه وبویراحمد',N'مارگون');
INSERT INTO City VALUES (N'کهگیلویه وبویراحمد',N'چرام');
INSERT INTO City VALUES (N'کهگیلویه وبویراحمد',N'سوق');
INSERT INTO City VALUES (N'گلستان',N'سیمین شهر');
INSERT INTO City VALUES (N'گلستان',N'مزرعه');
INSERT INTO City VALUES (N'گلستان',N'رامیان');
INSERT INTO City VALUES (N'گلستان',N'فراغی');
INSERT INTO City VALUES (N'گلستان',N'گنبدکاووس');
INSERT INTO City VALUES (N'گلستان',N'کردکوی');
INSERT INTO City VALUES (N'گلستان',N'مراوه');
INSERT INTO City VALUES (N'گلستان',N'بندرترکمن');
INSERT INTO City VALUES (N'گلستان',N'نگین شهر');
INSERT INTO City VALUES (N'گلستان',N'آق قلا');
INSERT INTO City VALUES (N'گلستان',N'سرخنکلاته');
INSERT INTO City VALUES (N'گلستان',N'گالیکش');
INSERT INTO City VALUES (N'گلستان',N'سنگدوین');
INSERT INTO City VALUES (N'گلستان',N'دلند');
INSERT INTO City VALUES (N'گلستان',N'بندرگز');
INSERT INTO City VALUES (N'گلستان',N'نوده خاندوز');
INSERT INTO City VALUES (N'گلستان',N'مینودشت');
INSERT INTO City VALUES (N'گلستان',N'گرگان');
INSERT INTO City VALUES (N'گلستان',N'گمیش تپه');
INSERT INTO City VALUES (N'گلستان',N'علی اباد');
INSERT INTO City VALUES (N'گلستان',N'خان ببین');
INSERT INTO City VALUES (N'گلستان',N'کلاله');
INSERT INTO City VALUES (N'گلستان',N'اینچه برون');
INSERT INTO City VALUES (N'گلستان',N'فاضل آباد');
INSERT INTO City VALUES (N'گلستان',N'تاتارعلیا');
INSERT INTO City VALUES (N'گلستان',N'نوکنده');
INSERT INTO City VALUES (N'گلستان',N'آزادشهر');
INSERT INTO City VALUES (N'گلستان',N'انبارآلوم');
INSERT INTO City VALUES (N'گلستان',N'جلین');
INSERT INTO City VALUES (N'گیلان',N'منجیل');
INSERT INTO City VALUES (N'گیلان',N'شلمان');
INSERT INTO City VALUES (N'گیلان',N'خشکبیجار');
INSERT INTO City VALUES (N'گیلان',N'ماکلوان');
INSERT INTO City VALUES (N'گیلان',N'سنگر');
INSERT INTO City VALUES (N'گیلان',N'مرجقل');
INSERT INTO City VALUES (N'گیلان',N'لیسار');
INSERT INTO City VALUES (N'گیلان',N'رضوانشهر');
INSERT INTO City VALUES (N'گیلان',N'رحیم آباد');
INSERT INTO City VALUES (N'گیلان',N'لوندویل');
INSERT INTO City VALUES (N'گیلان',N'احمدسرگوراب');
INSERT INTO City VALUES (N'گیلان',N'لوشان');
INSERT INTO City VALUES (N'گیلان',N'اطاقور');
INSERT INTO City VALUES (N'گیلان',N'لشت نشاء');
INSERT INTO City VALUES (N'گیلان',N'فومن');
INSERT INTO City VALUES (N'گیلان',N'چوبر');
INSERT INTO City VALUES (N'گیلان',N'بازار جمعه');
INSERT INTO City VALUES (N'گیلان',N'کلاچای');
INSERT INTO City VALUES (N'گیلان',N'بندرانزلی');
INSERT INTO City VALUES (N'گیلان',N'املش');
INSERT INTO City VALUES (N'گیلان',N'رستم آباد');
INSERT INTO City VALUES (N'گیلان',N'لاهیجان');
INSERT INTO City VALUES (N'گیلان',N'توتکابن');
INSERT INTO City VALUES (N'گیلان',N'لنگرود');
INSERT INTO City VALUES (N'گیلان',N'کوچصفهان');
INSERT INTO City VALUES (N'گیلان',N'صومعه سرا');
INSERT INTO City VALUES (N'گیلان',N'اسالم');
INSERT INTO City VALUES (N'گیلان',N'دیلمان');
INSERT INTO City VALUES (N'گیلان',N'رودسر');
INSERT INTO City VALUES (N'گیلان',N'کیاشهر');
INSERT INTO City VALUES (N'گیلان',N'شفت');
INSERT INTO City VALUES (N'گیلان',N'رودبار');
INSERT INTO City VALUES (N'گیلان',N'کومله');
INSERT INTO City VALUES (N'گیلان',N'رشت');
INSERT INTO City VALUES (N'گیلان',N'ماسوله');
INSERT INTO City VALUES (N'گیلان',N'خمام');
INSERT INTO City VALUES (N'گیلان',N'ماسال');
INSERT INTO City VALUES (N'گیلان',N'واجارگاه');
INSERT INTO City VALUES (N'گیلان',N'هشتپر (تالش)');
INSERT INTO City VALUES (N'گیلان',N'پره سر');
INSERT INTO City VALUES (N'گیلان',N'بره سر');
INSERT INTO City VALUES (N'گیلان',N'آستارا');
INSERT INTO City VALUES (N'گیلان',N'رودبنه');
INSERT INTO City VALUES (N'گیلان',N'جیرنده');
INSERT INTO City VALUES (N'گیلان',N'چاف و چمخاله');
INSERT INTO City VALUES (N'گیلان',N'لولمان');
INSERT INTO City VALUES (N'گیلان',N'گوراب زرمیخ');
INSERT INTO City VALUES (N'گیلان',N'حویق');
INSERT INTO City VALUES (N'گیلان',N'سیاهکل');
INSERT INTO City VALUES (N'گیلان',N'چابکسر');
INSERT INTO City VALUES (N'گیلان',N'آستانه اشرفیه');
INSERT INTO City VALUES (N'گیلان',N'رانکوه');
INSERT INTO City VALUES (N'لرستان',N'چالانچولان');
INSERT INTO City VALUES (N'لرستان',N'بیران شهر');
INSERT INTO City VALUES (N'لرستان',N'ویسیان');
INSERT INTO City VALUES (N'لرستان',N'شول آباد');
INSERT INTO City VALUES (N'لرستان',N'پلدختر');
INSERT INTO City VALUES (N'لرستان',N'کوهدشت');
INSERT INTO City VALUES (N'لرستان',N'هفت چشمه');
INSERT INTO City VALUES (N'لرستان',N'بروجرد');
INSERT INTO City VALUES (N'لرستان',N'الشتر');
INSERT INTO City VALUES (N'لرستان',N'مومن آباد');
INSERT INTO City VALUES (N'لرستان',N'دورود');
INSERT INTO City VALUES (N'لرستان',N'زاغه');
INSERT INTO City VALUES (N'لرستان',N'چقابل');
INSERT INTO City VALUES (N'لرستان',N'الیگودرز');
INSERT INTO City VALUES (N'لرستان',N'معمولان');
INSERT INTO City VALUES (N'لرستان',N'کوهنانی');
INSERT INTO City VALUES (N'لرستان',N'نورآباد');
INSERT INTO City VALUES (N'لرستان',N'سپیددشت');
INSERT INTO City VALUES (N'لرستان',N'سراب دوره');
INSERT INTO City VALUES (N'لرستان',N'ازنا');
INSERT INTO City VALUES (N'لرستان',N'گراب');
INSERT INTO City VALUES (N'لرستان',N'خرم آباد');
INSERT INTO City VALUES (N'لرستان',N'اشترینان');
INSERT INTO City VALUES (N'لرستان',N'فیروزآباد');
INSERT INTO City VALUES (N'لرستان',N'درب گنبد');
INSERT INTO City VALUES (N'مازندران',N'گلوگاه');
INSERT INTO City VALUES (N'مازندران',N'گلوگاه');
INSERT INTO City VALUES (N'مازندران',N'پل سفید');
INSERT INTO City VALUES (N'مازندران',N'دابودشت');
INSERT INTO City VALUES (N'مازندران',N'چالوس');
INSERT INTO City VALUES (N'مازندران',N'کیاسر');
INSERT INTO City VALUES (N'مازندران',N'بهنمیر');
INSERT INTO City VALUES (N'مازندران',N'تنکابن');
INSERT INTO City VALUES (N'مازندران',N'کلاردشت');
INSERT INTO City VALUES (N'مازندران',N'ایزدشهر');
INSERT INTO City VALUES (N'مازندران',N'گتاب');
INSERT INTO City VALUES (N'مازندران',N'سلمان شهر');
INSERT INTO City VALUES (N'مازندران',N'ارطه');
INSERT INTO City VALUES (N'مازندران',N'امیرکلا');
INSERT INTO City VALUES (N'مازندران',N'کوهی خیل');
INSERT INTO City VALUES (N'مازندران',N'پایین هولار');
INSERT INTO City VALUES (N'مازندران',N'گزنک');
INSERT INTO City VALUES (N'مازندران',N'محمودآباد');
INSERT INTO City VALUES (N'مازندران',N'رامسر');
INSERT INTO City VALUES (N'مازندران',N'نوشهر');
INSERT INTO City VALUES (N'مازندران',N'خلیل شهر');
INSERT INTO City VALUES (N'مازندران',N'کیاکلا');
INSERT INTO City VALUES (N'مازندران',N'نور');
INSERT INTO City VALUES (N'مازندران',N'مرزیکلا');
INSERT INTO City VALUES (N'مازندران',N'فریدونکنار');
INSERT INTO City VALUES (N'مازندران',N'زیرآب');
INSERT INTO City VALUES (N'مازندران',N'امامزاده عبدالله');
INSERT INTO City VALUES (N'مازندران',N'هچیرود');
INSERT INTO City VALUES (N'مازندران',N'فریم');
INSERT INTO City VALUES (N'مازندران',N'هادی شهر');
INSERT INTO City VALUES (N'مازندران',N'نشتارود');
INSERT INTO City VALUES (N'مازندران',N'پول');
INSERT INTO City VALUES (N'مازندران',N'بهشهر');
INSERT INTO City VALUES (N'مازندران',N'کلارآباد');
INSERT INTO City VALUES (N'مازندران',N'بلده');
INSERT INTO City VALUES (N'مازندران',N'بابل');
INSERT INTO City VALUES (N'مازندران',N'جویبار');
INSERT INTO City VALUES (N'مازندران',N'آلاشت');
INSERT INTO City VALUES (N'مازندران',N'آمل');
INSERT INTO City VALUES (N'مازندران',N'نکا');
INSERT INTO City VALUES (N'مازندران',N'کتالم وسادات شهر');
INSERT INTO City VALUES (N'مازندران',N'بابلسر');
INSERT INTO City VALUES (N'مازندران',N'شیرود');
INSERT INTO City VALUES (N'مازندران',N'شیرگاه');
INSERT INTO City VALUES (N'مازندران',N'رویان');
INSERT INTO City VALUES (N'مازندران',N'زرگرمحله');
INSERT INTO City VALUES (N'مازندران',N'عباس اباد');
INSERT INTO City VALUES (N'مازندران',N'قایم شهر');
INSERT INTO City VALUES (N'مازندران',N'خوش رودپی');
INSERT INTO City VALUES (N'مازندران',N'مرزن آباد');
INSERT INTO City VALUES (N'مازندران',N'ساری');
INSERT INTO City VALUES (N'مازندران',N'رینه');
INSERT INTO City VALUES (N'مازندران',N'سرخرود');
INSERT INTO City VALUES (N'مازندران',N'خرم آباد');
INSERT INTO City VALUES (N'مازندران',N'کجور');
INSERT INTO City VALUES (N'مازندران',N'رستمکلا');
INSERT INTO City VALUES (N'مازندران',N'سورک');
INSERT INTO City VALUES (N'مازندران',N'چمستان');
INSERT INTO City VALUES (N'مرکزی',N'آستانه');
INSERT INTO City VALUES (N'مرکزی',N'خنجین');
INSERT INTO City VALUES (N'مرکزی',N'نراق');
INSERT INTO City VALUES (N'مرکزی',N'کمیجان');
INSERT INTO City VALUES (N'مرکزی',N'آشتیان');
INSERT INTO City VALUES (N'مرکزی',N'رازقان');
INSERT INTO City VALUES (N'مرکزی',N'مهاجران');
INSERT INTO City VALUES (N'مرکزی',N'غرق آباد');
INSERT INTO City VALUES (N'مرکزی',N'خنداب');
INSERT INTO City VALUES (N'مرکزی',N'قورچی باشی');
INSERT INTO City VALUES (N'مرکزی',N'خشکرود');
INSERT INTO City VALUES (N'مرکزی',N'ساروق');
INSERT INTO City VALUES (N'مرکزی',N'محلات');
INSERT INTO City VALUES (N'مرکزی',N'شازند');
INSERT INTO City VALUES (N'مرکزی',N'ساوه');
INSERT INTO City VALUES (N'مرکزی',N'میلاجرد');
INSERT INTO City VALUES (N'مرکزی',N'تفرش');
INSERT INTO City VALUES (N'مرکزی',N'زاویه');
INSERT INTO City VALUES (N'مرکزی',N'اراک');
INSERT INTO City VALUES (N'مرکزی',N'توره');
INSERT INTO City VALUES (N'مرکزی',N'نوبران');
INSERT INTO City VALUES (N'مرکزی',N'فرمهین');
INSERT INTO City VALUES (N'مرکزی',N'دلیجان');
INSERT INTO City VALUES (N'مرکزی',N'پرندک');
INSERT INTO City VALUES (N'مرکزی',N'کارچان');
INSERT INTO City VALUES (N'مرکزی',N'نیمور');
INSERT INTO City VALUES (N'مرکزی',N'هندودر');
INSERT INTO City VALUES (N'مرکزی',N'آوه');
INSERT INTO City VALUES (N'مرکزی',N'جاورسیان');
INSERT INTO City VALUES (N'مرکزی',N'خمین');
INSERT INTO City VALUES (N'مرکزی',N'مامونیه');
INSERT INTO City VALUES (N'مرکزی',N'داودآباد');
INSERT INTO City VALUES (N'مرکزی',N'شهباز');
INSERT INTO City VALUES (N'هرمزگان',N'بیکاء');
INSERT INTO City VALUES (N'هرمزگان',N'تیرور');
INSERT INTO City VALUES (N'هرمزگان',N'گروک');
INSERT INTO City VALUES (N'هرمزگان',N'قشم');
INSERT INTO City VALUES (N'هرمزگان',N'کوشکنار');
INSERT INTO City VALUES (N'هرمزگان',N'کیش');
INSERT INTO City VALUES (N'هرمزگان',N'سرگز');
INSERT INTO City VALUES (N'هرمزگان',N'بندرعباس');
INSERT INTO City VALUES (N'هرمزگان',N'زیارتعلی');
INSERT INTO City VALUES (N'هرمزگان',N'سندرک');
INSERT INTO City VALUES (N'هرمزگان',N'کوهستک');
INSERT INTO City VALUES (N'هرمزگان',N'لمزان');
INSERT INTO City VALUES (N'هرمزگان',N'رویدر');
INSERT INTO City VALUES (N'هرمزگان',N'قلعه قاضی');
INSERT INTO City VALUES (N'هرمزگان',N'فارغان');
INSERT INTO City VALUES (N'هرمزگان',N'ابوموسی');
INSERT INTO City VALUES (N'هرمزگان',N'هشتبندی');
INSERT INTO City VALUES (N'هرمزگان',N'سردشت');
INSERT INTO City VALUES (N'هرمزگان',N'درگهان');
INSERT INTO City VALUES (N'هرمزگان',N'پارسیان');
INSERT INTO City VALUES (N'هرمزگان',N'کنگ');
INSERT INTO City VALUES (N'هرمزگان',N'جناح');
INSERT INTO City VALUES (N'هرمزگان',N'تازیان پایین');
INSERT INTO City VALUES (N'هرمزگان',N'دهبارز');
INSERT INTO City VALUES (N'هرمزگان',N'میناب');
INSERT INTO City VALUES (N'هرمزگان',N'سیریک');
INSERT INTO City VALUES (N'هرمزگان',N'سوزا');
INSERT INTO City VALUES (N'هرمزگان',N'خمیر');
INSERT INTO City VALUES (N'هرمزگان',N'چارک');
INSERT INTO City VALUES (N'هرمزگان',N'حاجی اباد');
INSERT INTO City VALUES (N'هرمزگان',N'فین');
INSERT INTO City VALUES (N'هرمزگان',N'بندرجاسک');
INSERT INTO City VALUES (N'هرمزگان',N'گوهران');
INSERT INTO City VALUES (N'هرمزگان',N'هرمز');
INSERT INTO City VALUES (N'هرمزگان',N'دشتی');
INSERT INTO City VALUES (N'هرمزگان',N'بندرلنگه');
INSERT INTO City VALUES (N'هرمزگان',N'بستک');
INSERT INTO City VALUES (N'هرمزگان',N'تخت');
INSERT INTO City VALUES (N'همدان',N'زنگنه');
INSERT INTO City VALUES (N'همدان',N'دمق');
INSERT INTO City VALUES (N'همدان',N'سرکان');
INSERT INTO City VALUES (N'همدان',N'آجین');
INSERT INTO City VALUES (N'همدان',N'جورقان');
INSERT INTO City VALUES (N'همدان',N'برزول');
INSERT INTO City VALUES (N'همدان',N'فامنین');
INSERT INTO City VALUES (N'همدان',N'سامن');
INSERT INTO City VALUES (N'همدان',N'بهار');
INSERT INTO City VALUES (N'همدان',N'فرسفج');
INSERT INTO City VALUES (N'همدان',N'شیرین سو');
INSERT INTO City VALUES (N'همدان',N'مریانج');
INSERT INTO City VALUES (N'همدان',N'فیروزان');
INSERT INTO City VALUES (N'همدان',N'قروه درجزین');
INSERT INTO City VALUES (N'همدان',N'ازندریان');
INSERT INTO City VALUES (N'همدان',N'لالجین');
INSERT INTO City VALUES (N'همدان',N'گل تپه');
INSERT INTO City VALUES (N'همدان',N'گیان');
INSERT INTO City VALUES (N'همدان',N'ملایر');
INSERT INTO City VALUES (N'همدان',N'صالح آباد');
INSERT INTO City VALUES (N'همدان',N'تویسرکان');
INSERT INTO City VALUES (N'همدان',N'اسدآباد');
INSERT INTO City VALUES (N'همدان',N'همدان');
INSERT INTO City VALUES (N'همدان',N'نهاوند');
INSERT INTO City VALUES (N'همدان',N'رزن');
INSERT INTO City VALUES (N'همدان',N'جوکار');
INSERT INTO City VALUES (N'همدان',N'مهاجران');
INSERT INTO City VALUES (N'همدان',N'کبودرآهنگ');
INSERT INTO City VALUES (N'همدان',N'قهاوند');
INSERT INTO City VALUES (N'یزد',N'مروست');
INSERT INTO City VALUES (N'یزد',N'مهردشت');
INSERT INTO City VALUES (N'یزد',N'حمیدیا');
INSERT INTO City VALUES (N'یزد',N'تفت');
INSERT INTO City VALUES (N'یزد',N'اشکذر');
INSERT INTO City VALUES (N'یزد',N'ندوشن');
INSERT INTO City VALUES (N'یزد',N'یزد');
INSERT INTO City VALUES (N'یزد',N'عقدا');
INSERT INTO City VALUES (N'یزد',N'بهاباد');
INSERT INTO City VALUES (N'یزد',N'ابرکوه');
INSERT INTO City VALUES (N'یزد',N'زارچ');
INSERT INTO City VALUES (N'یزد',N'نیر');
INSERT INTO City VALUES (N'یزد',N'اردکان');
INSERT INTO City VALUES (N'یزد',N'هرات');
INSERT INTO City VALUES (N'یزد',N'بفروییه');
INSERT INTO City VALUES (N'یزد',N'شاهدیه');
INSERT INTO City VALUES (N'یزد',N'بافق');
INSERT INTO City VALUES (N'یزد',N'خضرآباد');
INSERT INTO City VALUES (N'یزد',N'میبد');
INSERT INTO City VALUES (N'یزد',N'مهریز');
INSERT INTO City VALUES (N'یزد',N'احمدآباد');
